; PlatformIO Project Configuration File

[platformio]
default_envs = olimex-poe

[firmware]
name = HSG-LEDController-ESP32-POE-FW
short_name = HSG LED Controller
maker = Hugh Kojack
github_url = https://github.com/hughkojack/LED-Controller

[env:base]
; --- Common settings for all environments ---
platform = espressif32@6.7.0
board = esp32-poe
framework = espidf
monitor_speed = 115200
build_flags = 
    -Icomponents/hsg_api
    -Icomponents/hsg_outputs
    -DFW_NAME='"${firmware.name}"'
    -DFW_SHORT_NAME='"${firmware.short_name}"'
    -DFW_MAKER='"${firmware.maker}"'
    -DFW_GITHUB_URL='"${firmware.github_url}"'

; --- Environment for the Olimex ESP32-POE board ---
[env:olimex-poe]
extends = env:base
board_build.partitions = partitions.csv
board_build.app_partition_name = app0
extra_scripts =
    pre:extra_scripts/pre_embed.py
build_flags = 
    ${env.build_flags}
    -D BOARD_OLIMEX_POE
    -D IDF_SKIP_GIT_REVISION=1
board_build.sdkconfig = sdkconfig.olimex-poe
; PlatformIO's checkprogsize uses a conservative default max size for esp32-poe.
; Our `partitions.csv` allocates 1900K for app0/app1.
board_upload.maximum_size = 1851392

; --- Environment for the Rack32 board ---
[env:rack32]
extends = env:base
build_flags = 
    ${env.build_flags}
    -D BOARD_RACK32
board_build.sdkconfig = sdkconfig.rack32